version: '3.8'

volumes:
  postgres_data_test:

services:
  backend:
    build: ./backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend/:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env
#    depends_on:
#      - db_debug
      # - redis
#
#  db_debug:
#    image: postgres:12.3
#    volumes:
#      - postgres_data_test:/var/lib/postgresql/data/
#    environment:
#      - POSTGRES_USER=hello_django
#      - POSTGRES_PASSWORD=hello_django
#      - POSTGRES_DB=hello_django_dev
#
#  redis:
#    image: redis:6.0.8-alpine
#
#  celery:
#    build: ./django-app
#    command: celery -A backend worker -P gevent -c 2 -l info
#    volumes:
#      - ./django-app/:/usr/src/app/
#    env_file:
#      - ./.env.dev
#    depends_on:
#      - db_debug
#      - redis
