# docker exec -ti $(docker ps --filter expose=8000 -q) sh -c "python manage.py create_disabled_alerts"
from datetime import datetime

from django.core.management.base import BaseCommand

from app.models import MeasureType, MeasurementAlert, TimeseriesData


class Command(BaseCommand):
    help = 'Todo.'

    def _parse_str_to_datetime(self, s):
        return datetime.strptime(s, '%Y-%m-%d').replace(hour=0, minute=0)

    def handle(self, **options):
        info = self.stdout.write

        #  TODO: flushed =(
        MeasurementAlert.objects.all().delete()

        to_save_1 = [
        TimeseriesData(measurement=MeasureType.GOOG, timestamp=self._parse_str_to_datetime("2020-02-20"), value=75.907),
        TimeseriesData(measurement=MeasureType.GOOG, timestamp=self._parse_str_to_datetime("2020-02-21"), value=74.255),
        TimeseriesData(measurement=MeasureType.GOOG, timestamp=self._parse_str_to_datetime("2020-02-24"), value=71.079),
        TimeseriesData(measurement=MeasureType.GOOG, timestamp=self._parse_str_to_datetime("2020-02-25"), value=69.422),
        TimeseriesData(measurement=MeasureType.GOOG, timestamp=self._parse_str_to_datetime("2020-02-26"), value=69.658),
        TimeseriesData(measurement=MeasureType.GOOG, timestamp=self._parse_str_to_datetime("2020-02-27"), value=65.904),
        TimeseriesData(measurement=MeasureType.GOOG, timestamp=self._parse_str_to_datetime("2020-02-28"), value=66.966),
        TimeseriesData(measurement=MeasureType.GOOG, timestamp=self._parse_str_to_datetime("2020-03-02"), value=69.455),
        TimeseriesData(measurement=MeasureType.GOOG, timestamp=self._parse_str_to_datetime("2020-03-03"), value=67.069),
        TimeseriesData(measurement=MeasureType.GOOG, timestamp=self._parse_str_to_datetime("2020-03-04"), value=69.325),
        TimeseriesData(measurement=MeasureType.GOOG, timestamp=self._parse_str_to_datetime("2020-03-05"), value=65.952),
        TimeseriesData(measurement=MeasureType.GOOG, timestamp=self._parse_str_to_datetime("2020-03-06"), value=64.920),
        TimeseriesData(measurement=MeasureType.GOOG, timestamp=self._parse_str_to_datetime("2020-03-09"), value=60.777),
        TimeseriesData(measurement=MeasureType.GOOG, timestamp=self._parse_str_to_datetime("2020-03-10"), value=64.019),
        TimeseriesData(measurement=MeasureType.GOOG, timestamp=self._parse_str_to_datetime("2020-03-11"), value=60.770),
        TimeseriesData(measurement=MeasureType.GOOG, timestamp=self._parse_str_to_datetime("2020-03-12"), value=55.745),
        TimeseriesData(measurement=MeasureType.GOOG, timestamp=self._parse_str_to_datetime("2020-03-13"), value=60.986),
        TimeseriesData(measurement=MeasureType.GOOG, timestamp=self._parse_str_to_datetime("2020-03-16"), value=54.216),
        TimeseriesData(measurement=MeasureType.GOOG, timestamp=self._parse_str_to_datetime("2020-03-17"), value=55.990),
        TimeseriesData(measurement=MeasureType.GOOG, timestamp=self._parse_str_to_datetime("2020-03-18"), value=54.840),
        TimeseriesData(measurement=MeasureType.GOOG, timestamp=self._parse_str_to_datetime("2020-03-19"), value=55.764),
        TimeseriesData(measurement=MeasureType.GOOG, timestamp=self._parse_str_to_datetime("2020-03-20"), value=53.616),
        TimeseriesData(measurement=MeasureType.GOOG, timestamp=self._parse_str_to_datetime("2020-03-23"), value=52.831),
        TimeseriesData(measurement=MeasureType.GOOG, timestamp=self._parse_str_to_datetime("2020-03-24"), value=56.722),
        TimeseriesData(measurement=MeasureType.GOOG, timestamp=self._parse_str_to_datetime("2020-03-25"), value=55.124),
        TimeseriesData(measurement=MeasureType.GOOG, timestamp=self._parse_str_to_datetime("2020-03-26"), value=58.087),
        TimeseriesData(measurement=MeasureType.GOOG, timestamp=self._parse_str_to_datetime("2020-03-27"), value=55.535),
        TimeseriesData(measurement=MeasureType.GOOG, timestamp=self._parse_str_to_datetime("2020-03-30"), value=57.340),
        TimeseriesData(measurement=MeasureType.GOOG, timestamp=self._parse_str_to_datetime("2020-03-31"), value=58.140),
        TimeseriesData(measurement=MeasureType.GOOG, timestamp=self._parse_str_to_datetime("2020-04-01"), value=55.280),
        ]

        to_save_2 = [TimeseriesData(measurement=MeasureType.MSFT, timestamp=self._parse_str_to_datetime("2020-02-20"),
                       value=184.4199),
        TimeseriesData(measurement=MeasureType.MSFT, timestamp=self._parse_str_to_datetime("2020-02-21"),
                       value=178.5899),
        TimeseriesData(measurement=MeasureType.MSFT, timestamp=self._parse_str_to_datetime("2020-02-24"),
                       value=170.8899),
        TimeseriesData(measurement=MeasureType.MSFT, timestamp=self._parse_str_to_datetime("2020-02-25"),
                       value=168.0700),
        TimeseriesData(measurement=MeasureType.MSFT, timestamp=self._parse_str_to_datetime("2020-02-26"),
                       value=170.1699),
        TimeseriesData(measurement=MeasureType.MSFT, timestamp=self._parse_str_to_datetime("2020-02-27"),
                       value=158.1799),
        TimeseriesData(measurement=MeasureType.MSFT, timestamp=self._parse_str_to_datetime("2020-02-28"),
                       value=162.0099),
        TimeseriesData(measurement=MeasureType.MSFT, timestamp=self._parse_str_to_datetime("2020-03-02"),
                       value=172.7899),
        TimeseriesData(measurement=MeasureType.MSFT, timestamp=self._parse_str_to_datetime("2020-03-03"),
                       value=164.5099),
        TimeseriesData(measurement=MeasureType.MSFT, timestamp=self._parse_str_to_datetime("2020-03-04"),
                       value=170.5500),
        TimeseriesData(measurement=MeasureType.MSFT, timestamp=self._parse_str_to_datetime("2020-03-05"),
                       value=166.2700),
        TimeseriesData(measurement=MeasureType.MSFT, timestamp=self._parse_str_to_datetime("2020-03-06"),
                       value=161.5700),
        TimeseriesData(measurement=MeasureType.MSFT, timestamp=self._parse_str_to_datetime("2020-03-09"),
                       value=150.6199),
        TimeseriesData(measurement=MeasureType.MSFT, timestamp=self._parse_str_to_datetime("2020-03-10"),
                       value=160.9199),
        TimeseriesData(measurement=MeasureType.MSFT, timestamp=self._parse_str_to_datetime("2020-03-11"),
                       value=153.6300),
        TimeseriesData(measurement=MeasureType.MSFT, timestamp=self._parse_str_to_datetime("2020-03-12"),
                       value=139.0599),
        TimeseriesData(measurement=MeasureType.MSFT, timestamp=self._parse_str_to_datetime("2020-03-13"),
                       value=158.8300),
        TimeseriesData(measurement=MeasureType.MSFT, timestamp=self._parse_str_to_datetime("2020-03-16"),
                       value=135.4199),
        TimeseriesData(measurement=MeasureType.MSFT, timestamp=self._parse_str_to_datetime("2020-03-17"),
                       value=146.5700),
        TimeseriesData(measurement=MeasureType.MSFT, timestamp=self._parse_str_to_datetime("2020-03-18"),
                       value=140.3999),
        TimeseriesData(measurement=MeasureType.MSFT, timestamp=self._parse_str_to_datetime("2020-03-19"),
                       value=142.7100),
        TimeseriesData(measurement=MeasureType.MSFT, timestamp=self._parse_str_to_datetime("2020-03-20"),
                       value=137.3500),
        TimeseriesData(measurement=MeasureType.MSFT, timestamp=self._parse_str_to_datetime("2020-03-23"),
                       value=135.9799),
        TimeseriesData(measurement=MeasureType.MSFT, timestamp=self._parse_str_to_datetime("2020-03-24"),
                       value=148.3399),
        TimeseriesData(measurement=MeasureType.MSFT, timestamp=self._parse_str_to_datetime("2020-03-25"),
                       value=146.9199),
        TimeseriesData(measurement=MeasureType.MSFT, timestamp=self._parse_str_to_datetime("2020-03-26"),
                       value=156.1100),
        TimeseriesData(measurement=MeasureType.MSFT, timestamp=self._parse_str_to_datetime("2020-03-27"),
                       value=149.6999),
        TimeseriesData(measurement=MeasureType.MSFT, timestamp=self._parse_str_to_datetime("2020-03-30"),
                       value=160.2299),
        TimeseriesData(measurement=MeasureType.MSFT, timestamp=self._parse_str_to_datetime("2020-03-31"),
                       value=157.7100),
        TimeseriesData(measurement=MeasureType.MSFT, timestamp=self._parse_str_to_datetime("2020-04-01"),
                       value=152.1100),]

        to_save_3 = [
            TimeseriesData(measurement=MeasureType.AAPL, timestamp=self._parse_str_to_datetime("2020-02-20"),
                           value=80.074),
            TimeseriesData(measurement=MeasureType.AAPL, timestamp=self._parse_str_to_datetime("2020-02-21"),
                           value=78.262),
            TimeseriesData(measurement=MeasureType.AAPL, timestamp=self._parse_str_to_datetime("2020-02-24"),
                           value=74.544),
            TimeseriesData(measurement=MeasureType.AAPL, timestamp=self._parse_str_to_datetime("2020-02-25"),
                           value=72.019),
            TimeseriesData(measurement=MeasureType.AAPL, timestamp=self._parse_str_to_datetime("2020-02-26"),
                           value=73.162),
            TimeseriesData(measurement=MeasureType.AAPL, timestamp=self._parse_str_to_datetime("2020-02-27"),
                           value=68.379),
            TimeseriesData(measurement=MeasureType.AAPL, timestamp=self._parse_str_to_datetime("2020-02-28"),
                           value=68.339),
            TimeseriesData(measurement=MeasureType.AAPL, timestamp=self._parse_str_to_datetime("2020-03-02"),
                           value=74.702),
            TimeseriesData(measurement=MeasureType.AAPL, timestamp=self._parse_str_to_datetime("2020-03-03"),
                           value=72.330),
            TimeseriesData(measurement=MeasureType.AAPL, timestamp=self._parse_str_to_datetime("2020-03-04"),
                           value=75.684),
            TimeseriesData(measurement=MeasureType.AAPL, timestamp=self._parse_str_to_datetime("2020-03-05"),
                           value=73.230),
            TimeseriesData(measurement=MeasureType.AAPL, timestamp=self._parse_str_to_datetime("2020-03-06"),
                           value=72.257),
            TimeseriesData(measurement=MeasureType.AAPL, timestamp=self._parse_str_to_datetime("2020-03-09"),
                           value=66.542),
            TimeseriesData(measurement=MeasureType.AAPL, timestamp=self._parse_str_to_datetime("2020-03-10"),
                           value=71.334),
            TimeseriesData(measurement=MeasureType.AAPL, timestamp=self._parse_str_to_datetime("2020-03-11"),
                           value=68.857),
            TimeseriesData(measurement=MeasureType.AAPL, timestamp=self._parse_str_to_datetime("2020-03-12"),
                           value=62.057),
            TimeseriesData(measurement=MeasureType.AAPL, timestamp=self._parse_str_to_datetime("2020-03-13"),
                           value=69.492),
            TimeseriesData(measurement=MeasureType.AAPL, timestamp=self._parse_str_to_datetime("2020-03-16"),
                           value=60.552),
            TimeseriesData(measurement=MeasureType.AAPL, timestamp=self._parse_str_to_datetime("2020-03-17"),
                           value=63.215),
            TimeseriesData(measurement=MeasureType.AAPL, timestamp=self._parse_str_to_datetime("2020-03-18"),
                           value=61.667),
            TimeseriesData(measurement=MeasureType.AAPL, timestamp=self._parse_str_to_datetime("2020-03-19"),
                           value=61.194),
            TimeseriesData(measurement=MeasureType.AAPL, timestamp=self._parse_str_to_datetime("2020-03-20"),
                           value=57.310),
            TimeseriesData(measurement=MeasureType.AAPL, timestamp=self._parse_str_to_datetime("2020-03-23"),
                           value=56.092),
            TimeseriesData(measurement=MeasureType.AAPL, timestamp=self._parse_str_to_datetime("2020-03-24"),
                           value=61.720),
            TimeseriesData(measurement=MeasureType.AAPL, timestamp=self._parse_str_to_datetime("2020-03-25"),
                           value=61.380),
            TimeseriesData(measurement=MeasureType.AAPL, timestamp=self._parse_str_to_datetime("2020-03-26"),
                           value=64.610),
            TimeseriesData(measurement=MeasureType.AAPL, timestamp=self._parse_str_to_datetime("2020-03-27"),
                           value=61.935),
            TimeseriesData(measurement=MeasureType.AAPL, timestamp=self._parse_str_to_datetime("2020-03-30"),
                           value=63.702),
            TimeseriesData(measurement=MeasureType.AAPL, timestamp=self._parse_str_to_datetime("2020-03-31"),
                           value=63.572),
            TimeseriesData(measurement=MeasureType.AAPL, timestamp=self._parse_str_to_datetime("2020-04-01"),
                           value=60.227),
        ]

        TimeseriesData.objects.bulk_create(to_save_1 + to_save_2 + to_save_3)
