# Generated by Django 4.2.7 on 2023-11-11 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MenuSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='Title')),
            ],
        ),
        migrations.CreateModel(
            name='TimeseriesData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measurement', models.IntegerField(choices=[(1, 'SMP500 Stocks, USD'), (2, 'NASDAQ Stocks, USD')], db_index=True)),
                ('value', models.FloatField()),
                ('timestamp', models.DateTimeField()),
            ],
            options={
                'ordering': ('-timestamp',),
            },
        ),
        migrations.CreateModel(
            name='MeasurementAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measurement', models.IntegerField(choices=[(1, 'SMP500 Stocks, USD'), (2, 'NASDAQ Stocks, USD')], db_index=True)),
                ('active', models.BooleanField(default=True, help_text='TODO: It could be deprecated when created and released used.')),
            ],
            options={
                'unique_together': {('measurement', 'active')},
            },
        ),
    ]
