# Generated by Django 4.2.7 on 2023-11-11 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurementalert',
            name='measurement',
            field=models.IntegerField(choices=[(1, 'GOOG, USD'), (2, 'MSFT, USD'), (3, 'AAPL, USD')], db_index=True),
        ),
        migrations.AlterField(
            model_name='timeseriesdata',
            name='measurement',
            field=models.IntegerField(choices=[(1, 'GOOG, USD'), (2, 'MSFT, USD'), (3, 'AAPL, USD')], db_index=True),
        ),
    ]
